### ISSUE TITLE
Implement keyboard shortcut

### ISSUE THREAD

**Issue by dvlden** [dvlden/ultrawideo#1]
As suggested by Yaiba Kurogane:
https://chrome.google.com/webstore/detail/ultrawideo/bfbnagnphiehemkdgmmficmjfddgfhpl/support

**Comment by dvlden** [comment]
Solved in #b2ea105c48970dd88422a8074966c3edf287b852

**Comment by UniqueC0de** [comment]
@dvlden: keyboard shortcut just don't work for me.
I'm not sure if it is conflict with other extensions's keyboard shortcut or not.
Please add configuration for keyboard shortcut, we can assign other key.

**Comment by UniqueC0de** [comment]
I'm using Chrome on macOS High Sierra.
My HTML and Javascript skill not so good.
But you can learn from this extension which use Ctrl + Alt + C keystroke.
https://github.com/wltrsjames/Ultrawide-Video/blob/master/js/UltraWide.js

**Comment by dvlden** [comment]
`Ctrl + Alt + C` is already taken by Magnet app.
`Cmd + Alt + C` is already taken by Alfred app.

It's kind of hard to make this shortcut for toggling, I'll try if it can be something like:
`Ctrl + Alt + Shift + Arrow Keys`

Will find some time later to test this and make updates if it works on every OS.

**Comment by dvlden** [comment]
In version 1.5.0 new keystrokes have been implemented and tested.

Mac:
`cmd + shift + 0` - toggle modes
`cmd + shift + 9` - toggle pause

Windows:
`ctrl + shift + 0` - toggle modes
`ctrl + shift + 9` - toggle pause

---

Extension will be pushed on each browser's extension store, very soon.
