### ISSUE TITLE
4:3 stretched to 16:9 aspect ratio

### ISSUE THREAD

**Issue by Hexaae** [dvlden/ultrawideo#101]
Would be great an option to switch (rare) 4:3 videos badly digitally converted resulting in squashed horizontally video frame. Stretching mode in your plugin is a life saver in this case, but still won't resize these rare videos with the correct proportions (still a little bit squashed horizontally)...
An option to force 4:3 to 16:9 (or to current screen aspect ratio automatically) would be great.

![image](https://user-images.githubusercontent.com/8591462/233416629-ca8c2753-177a-4085-b8db-30fadad11808.png)

**Comment by dvlden** [comment]
Hmmm, I'll think about it. Not sure how would I achieve something like this. 
Will try to use my package [Aspecter](https://github.com/dvlden/aspecter) to try to get the video AR and then force it to another.

**Comment by dvlden** [comment]
I did not implement this in v3 just yet, but I have plans for it in Pro version.
