### ISSUE TITLE
Disable auto detection and choose manually stretch mode

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#102]
Hello, my notebook is weak and auro detection can be risky because of "Autodetection frequency which determines how often we check for aspect ratio changes, more frequent aspect ratio checks can result in insane ram usage. Less frequent aspect ratio checks result in bigger delay between aspect ratio change and correction, shorter intervals are more responsive to changes in aspect ratio detections, but requires more system resources."

So i don't wish to use the auto detection feature please, i watch anime dragon ball in 4/3 format and i just have to manually choose stretching mode 16/9 and even if the stretch and aspect ratio are lost, i can reactivate it manually without needing the auto-detection feature that can run in the background and could use power and drain my battery or cause the fan to run noisy....

So please we hope an option to disable permanent auto-detection and an option to manually choose "persist stretch mode 16:9 by default il all websites", thank you very much !

**Comment by dvlden** [comment]
Hello,

The extension does not have any auto-detection feature implemented.
Can you elaborate?

Kind regards.

**Comment by trimechee** [comment]
Ahh ! I did not know that ! this is exactly what i was looking for and i was worried ! I said to myself since Ultrawideo removes the black bands by default and automatically, I said to myself surely Ultrawideo uses an internal mechanism to analyze the video and eliminate the black bands automatically .... but as Ultrawideo does not use auto detection automatic and lets the user automatically choose to stretch the video without auto-detection by default, then it's perfect and beautiful and it saves energy and preserves the battery and does not saturate the ram memory 🥇 👍  Thank you very much for this marvelous extension !

**Comment by trimechee** [comment]
In descripton of "Ultrawideo" : "The extension is smart enough to manipulate the video you put into a fullscreen, without affecting other video players."....that's why i was thinking there may be automatic auto detection feature by default....

**Comment by dvlden** [comment]
Nah, no auto detection. It uses the fullscreen mechanism. If you have 10 video players on one page, it will only affect the one that you put into the fullscreen. Hence, smart enough. ✌️

**Comment by trimechee** [comment]
Fantastic !! Thank you so much 🥇
