### ISSUE TITLE
Not working with Netflix platform

### ISSUE THREAD

**Issue by m4d0x** [dvlden/ultrawideo#108]
## Before Opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Information
I can assure you that this upscaler aint working correctly with Netflix on a 49" in 32:9, did work with youtube but not with Netflix.
Is there any way to fix this?

**Comment by dvlden** [comment]
Let me know if you ever decide to do this. 
Much appreciated!
