### ISSUE TITLE
Stretch only as far as filling one dimension

### ISSUE THREAD

**Issue by purple-pixie** [dvlden/ultrawideo#111]
(Watching on 3840 x 1080)

Currently players like Disney+ inexplicably show the image so it's entirely surrounded by black bars - above/below and also to the sides.

The functionality I was hoping for when I downloaded this was to make it maintain the aspect ratio but increase the size of the picture so it filled the screen vertically (keeping black bars horizontally)

The image might hopefully show what I mean

![image](https://github.com/dvlden/ultrawideo/assets/1550193/e7ca9487-f294-45a9-9772-5dc6f0c54989)

**Comment by dvlden** [comment]
There is already a request for that on #60 (discussions)
It will come in v3. It's a work in progress...

**Comment by dvlden** [comment]
Implemented in v3.
