### ISSUE TITLE
Would it be possible to have some build instructions?

### ISSUE THREAD

**Issue by momashi** [dvlden/ultrawideo#14]
Hi, I'm trying to build this project from source. So far I've tried:

cloning the github of the extension

and running:

npm run build
webpack --config webpack.config.js
webpack --progress --hide-modules --mode production

are there some dependencies needed?

**Comment by dvlden** [comment]
You'd need to:

```
npm i
npm run build
```

Nothing else is needed.

**Comment by momashi** [comment]
Thanks so, much!
