### ISSUE TITLE
Gesture Support as Alternative to Keyboard Shortcuts?

### ISSUE THREAD

**Issue by momashi** [dvlden/ultrawideo#15]
Would it be possible to add gesture support? Maybe pinch and unpinch to turn on and off Ultrawideo like in the youtube mobile app?

## Before Opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Information
Include as much detail as possible for this feature and why would it be useful or required to implement it.

**Comment by dvlden** [comment]
Are we talking about screen or about the trackpad?

**Comment by momashi** [comment]
I was thinking more for touch screens, seeing how keyboards aren't available when using tablets or phone.

**Comment by momashi** [comment]
It would be a nice thing to have when videos put text in the cropped areas, to be able to quickly toggle ultrawideo off and back on again.

**Comment by dvlden** [comment]
Does Chrome/Firefox or Opera even allow extension on Tablets and Phones?

**Comment by momashi** [comment]
I can't speak for Chrome or Opera but I am using your extension on Firefox Android and it works brilliantly.

**Comment by dvlden** [comment]
Oh wow, damn it. I did not know that such thing is possible. 
In that case, I think I should definitely consider making it work with such gestures for touch devices.

I'll keep this open.

**Comment by momashi** [comment]
Thanks, for that. It's very nice of you.

**Comment by dvlden** [comment]
I have a problem here of not owning an Android device, to install the Firefox browser and the extension. I can't see how this actually works on mobile currently so that I can improve further with touch events. 

I know it's been a while, to revisit this feature request, but you mentioned YouTube mobile app? Do Firefox extensions work outside the browser?

**Comment by ShalokShalom** [comment]
You can use one of the many Android Emulators, they do exist for Linux, Windows and macOS.

This one is the most used one:

https://www.bluestacks.com/

**Comment by pokekrishna** [comment]
I would love this feature too. Need it badly for this extension to shine on Firefox android. I will try if i can raise a PR, although I  not very good with JS
