### ISSUE TITLE
The "Toggle Pause" shortcut does not seem to work correctly

### ISSUE THREAD

**Issue by RobertYost** [dvlden/ultrawideo#17]
### Describe the bug
I've changed my "Toggle Pause" shortcut from the default, and it works fine when I toggle pause from on -> off, but it does not seem to work the other way (i.e. when I press that shortcut again, nothing happens)

### Reproduction steps
1. Use Toggle Pause shortcut
2. Use shortcut again

### Expected behavior
I think it should toggle Pause from off -> on when using it in the off state

### Environment
- **OS**: Windows 10.0 Build 18362
- **Browser**: Firefox 68.0.1 and Chrome 76.0.3809.100

**Comment by dvlden** [comment]
That's intended behavior. Pausing the extension via toggle or via shortcut entirely disables all event listeners. The only way to enable extension again is to manually toggle it. 

This won't change, because that's the functionality of it. Toggle mode to `normal` mode to restore the changes.
