### ISSUE TITLE
Doesn't work on Whale browser (Chromium based web browser)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [dvlden/ultrawideo#2]
Neither of the modes, between upscaling or stretching mode work, when simply using it on Youtube, even when watching videos in fullscreen, in fact, it doesn't work whatsoever. 
If it's not more of an issue with the user, like myself due to some stupid reasons i might i've produce to make this extension doesn't work, the work on a possible [obscure Korean browser](https://whale.naver.com/en/) might be not that interesting to do, so you can freely close this issue if it's preferred to concentrate your efforts on better known and used web browsers.

**Comment by dvlden** [comment]
Keyboard shortcuts are not working, I'll look into that today. Seems like I'm using some reserved keystrokes or something.

However, even tho I never heard about Whale browser, I just installed it and installed unpacked extension into it. 

Pause is working and modes are working... I don't have any issues with that whatsoever.

**Comment by PoorPocketsMcNewHold** [comment]
I've tried again, in incognito mode (to make sure, that all other extensions would be off, instead of Ultrawideo in which have allowed to be enabled there) and i was able to make it work, after disabling all the flags of browser. 
I've didn't really noticed the keyboard shortcuts being broken, as i don't use them, and don't really understand how it works, ⌘ seems to be representing the Windows or Apple key but i wasn't that sure. 
Sorry to have posted that issue, without thinking to that obvious (but wasn't for me, when checking the browser settings, script and extensions) detail.
I'll still let this issue open, since you've confirmed that keyboard shortcut wasn't working. If Windows/apple key + Up or Down key was the correct one, Indeed it's reserved for fullscreen/window switch[. (_I've already asked them to add more customizable shortcuts in the past, due to breaking with a voice program i was using_)](https://forum.whale.naver.com/topic/14781/)

**Comment by dvlden** [comment]
Resolved and responded on #1 

I will try to push this to Whale browser extension store as well.

**Comment by dvlden** [comment]
I tried to open an account on Naver and it got suspended right away.
Contacted the support and sent passport for verification. Waiting for response...

It's weird that mostly everything is on Chinese, but extension store is on English. 
Very hard to navigate...

**Comment by PoorPocketsMcNewHold** [comment]
*Korean.
I think it's mostly because they made a translated version of their browser forums and of their store, probably due to being the most useful for their small userbase outside of South Korea, but didn't translate it yet entirely on the other more "advanced" pages like the developer page.
Their extension "upload" guide should be there, entirely in Korean tho, like I've said. https://developers.whale.naver.com/distribution/ (Their built-in translator is especially got when translating Korean, so this should help)

**Comment by dvlden** [comment]
Oh, my bad...
Well, I think I must wait until they unblock and verify my account first.

**Comment by dvlden** [comment]
@PoorPocketsMcNewHold - Good news, my account was reviewed and unbanned. 
I have submitted the extension to their store as well. 

Once approved, I'll updated README on this repo, letting people know that it's now available for Whale Browser as well.

Thank you for your concern and interest!
