### ISSUE TITLE
18:9 upscale support

### ISSUE THREAD

**Issue by Vasllo** [dvlden/ultrawideo#21]
## Before Opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Information

Would it be possible to add 18:9 support to the upscale mode? Because with only 21:9 upscale mode and the rise of 18:9 content, I either watch with bars all around the content, or cut part of the content.

**Comment by dvlden** [comment]
Hello,

I answered this question in your previous open issue.

[#20 Comment](https://github.com/dvlden/ultrawideo/issues/20#issuecomment-529205189)
> Regarding your last question, it is not possible. The extension does not use any expensive JS calculations for the aspect ratio, but rather uses CSS so that the browser itself can handle this. If `object-fit` does not support it (as it does not at this time), it is not possible.
