### ISSUE TITLE
32:9

### ISSUE THREAD

**Issue by TheBlackSun** [dvlden/ultrawideo#22]
### Description
21:9 is fine - but 32:9 doesn't work properly.
Tried to watch Alien on Amazon Video, saw it came letterboxed. (Oh, I hate when the letterbox is actually rendered into the video file...) So I got the extention, and it does what it was designed to do, I assume - stretch removes the letterbox, but stretches the video too wide. Upscale does not stretch, but cuts the top and bottom of the video off - not just the bars, but what feels like about a quarter of the video's height.

### Expected behavior
I expected the upscale to scale vertically, thereby just removing the letterbox and resulting in black borders left and right of the video, rather than going by horizontal scaling. That, or allowing the scaler to work outside of fullscreen mode, so I can resize the window into 21:9 ratio for it to cut just the letterbox.

I switched to the Addon "Utrawidify" instead, which works for my screen. It supports an automatic ratio detection, where technically possible, but also a manual "Zoom slider" for the video - I used that zoom to adjust it manually and it works very well. Just as an example for options to increase compatibility of your addon!

**Comment by dvlden** [comment]
Not possible. 
https://github.com/dvlden/ultrawideo/issues/11#issuecomment-501668994
