### ISSUE TITLE
Latest update kills Youtube functionality

### ISSUE THREAD

**Issue by kunio55** [dvlden/ultrawideo#26]
Description
Extension no longer works with YouTube on Firefox mobile android in normal mode. Videos now display in default stretched form as they would without the extension.

Installing old V 2.0.2 fixes the issue

Repeatable with widescreen view in YouTube in normal mode

Expected behavior
Videos should display in fixed aspect ratio

Environment
- **OS**: Android 9 Galaxy Note 8
Browser: Firefox 68.4.1

**Comment by dvlden** [comment]
Hello @kunio55,

Thank you for your report on the proper spot. 

In the past, `Normal` mode was not doing anything, except modifying the `width` & `height` of the actual video container, in case that streaming platforms make them smaller in percentage for unknown reasons. 

I thought that this is not supposed to be happening, as `Normal` purpose is to simply restore the video to its original state. 

Can you tell me if `Upscale` mode does what you expect on Android device or shall I restore this behavior where `Normal` mode actually modifies size?

**Comment by pecmertens** [comment]
Hi, I have the same issue. Without the UltraWideo add-on, Youtube would zoom the video to fit my screen, dropping content from the top and bottom. With your add-on, the 'Normal' mode corrected this and displayed the Youtune videos in their correct aspect ratio, showing all content but with black bars left and right for 16:9 content (my phone being 19:9, I believe).

Done the latest update the 'Normal' mode doesn't do anything and displays Youtube videos identically to the situation without the add-on, i.e. stretched and dropping the top and bottom of the video. I would greatly appreciate it you could restore the old behavior of 'Normal' mode.

**Comment by dvlden** [comment]
Hello,

Thank you for stepping into this issue to contribute and help to resolve it.
I am not quite sure what is wrong, as I don't have an android device and on iOS I use the actual YouTube App, not watching from the browser.

Anyway, I have restored the functionality and made a quick patch update on Firefox only. 
Can you guys check `v2.1.1` and confirm back, is it working?

**Comment by kunio55** [comment]
Hi  @dvlden 
Thank you for responding so quickly. @pecmertens has the same exact same use case I was referring to. YouTube defaults to stretch videos and cuts off content and I use your addon to view content properly.

I installed V.2.1.1 and it is now "normal" mode works as I anticipated before

Thank you so much for your work!

**Comment by pecmertens** [comment]
Wow thank you @dvlden! That's way fast; it works perfectly again! You have a donate button somewhere?

**Comment by dvlden** [comment]
Hey, no worries. Glad it works again!

Donate button is only present in the post installation screen or on Firefox page of this extension, there’s ‘Contribute ❤️’ button. 

Here’s direct link to my PP, to save you some time searching. 
https://www.paypal.com/paypalme2/dvlden

Thanks in advance for the support and spread the word is also one of the best ways to contribute!

Regards,
Nenad Novakovic.

**Comment by pagefault** [comment]
Hi. This fix worked until yesterday but now the problem is back. Maybe it's related to the other open issue about it randomly stopping to work because the add-on version seems to still be 2.1.1 for me.
