### ISSUE TITLE
Extension will randomly stop working

### ISSUE THREAD

**Issue by scrubborn** [dvlden/ultrawideo#29]
I'm on the latest firefox on windows 10, recently the extension has just stopped working. It'll be fine earlier in the day and out of no where the shortcut just doesn't respond. All my videos will be either locked in 16:9 or 21:9 depending on what i was using last.  
  
The issue persists across all websites, but weirdly enough when I use the shortcut in disney+ the subtitles do change position on the screen as they should, the actual video though does not budge and is locked in 16:9

**Comment by dvlden** [comment]
Can you tell me are the shortcuts custom configured or defaults?
