### ISSUE TITLE
[YouTube TV] Incompatibility

### ISSUE THREAD

**Issue by AKInterrobang** [dvlden/ultrawideo#31]
## Before opening
Searched "YouTube TV" and "YouTubeTV" – no results.

### Describe the bug
When opening YouTube TV and clicking on fullscreen, the video does not zoom automatically. Changing modes via shortcuts or via the extension trigger does not work, nor does pausing and unpausing via the extension.

I would imagine this is because YouTube TV isn't true fullscreen, rather it still has the ability to scroll and see other videos even when you're in full-screen mode.

### Reproduction steps
- authenticate on YouTube TV
- find a video to watch
- make it fullscreen

### Expected behavior
The video is expected to open in zoomed fullscreen for ultrawide support.

### Environment
- **OS**: Windows 10 - 64 bit 
- **Browser**: Chrome 64 bit - 81.0.4044.138

**Comment by dvlden** [comment]
Hello @AKInterrobang,

Thank you for opening an issue. If it's not really going into full-screen when you click the button, then this extension won't work for it. 

Can you e-mail me your credentials, so that I can check it out?
`n.dvlden@gmail.com`

**Comment by dvlden** [comment]
Still looking for credentials. Nobody who's using YouTube TV has reached out to me, yet.
Closing until then.
