### ISSUE TITLE
[Netflix] Next-video option removes the extension changes.

### ISSUE THREAD

**Issue by damooch** [dvlden/ultrawideo#32]
### Describe the bug
While watching the series on Netflix, after an episode ends and you proceed to "watch next episode", the video will lose all modifications applied by the extension. _(restores back to normal)_

**This was not an issue a month ago...**

### Reproduction steps
- play any series on Netflix
- make it fullscreen
- proceed to the "next episode"

### Expected behavior
It should keep the selected mode from the extension.

### Environment
- **OS**: Windows 10 (latest update)
- **Browser**: Opera GX (latest update)

**Comment by dvlden** [comment]
Hello David,

Can you tell me if you downloaded the latest version from Chrome Web Store? 
Because Opera hasn't approved the last two or three releases and I'm thinking to deprecate it soon, from the Opera add-ons store.

Regards.

**Comment by damooch** [comment]
I can use the chrome web add on and use it that way and get back to you

**Comment by damooch** [comment]
It still doesn’t work on Netflix. The video goes back to 1080p non ultra
wide. If your only going to support chrome that’s a sad day. You are going
to see more and more people want to move away from the Google technocracy

**Comment by dvlden** [comment]
I will do some tests in a couple of days. Too busy with my daily job. 

No, Opera is WebKit, like Chrome, and their web-store and approval is very poor. So that doesn't mean supporting only Chrome, but all WebKit browsers, but being available on Chrome Webstore and Firefox store only.

**Comment by dvlden** [comment]
You are absolutely right. 
I'll investigate and see if this can be fixed.

**Comment by dvlden** [comment]
Reporting in. 
There's no solution to this from my POV. I've been debugging for an hour and couldn't find a solution. 

It is unfortunate, but Netflix replaces the entire video element with a new one and the extension is unable to detect that until fullscreen is toggled again. I even tried `MutationObserver` without success. 

If anyone would like to tackle this, feel free to make a PR.

**Comment by dvlden** [comment]
Closing this issue after further investigation. There's no solution to this at this time.
While an element is in fullscreen, removing that element and replacing it with another one, doesn't trigger the fullscreen event again, so there's no way to catch it.

**Comment by damooch** [comment]
Actually it is super easy you write into the script that when the slip into
button shows you minimize and maximize the window again as a work around.

**Comment by damooch** [comment]
Skip intro button

**Comment by dvlden** [comment]
Well, that would be Netflix's workaround feature only, which I'd avoid. 
The whole purpose of this extension is to work on every platform, where possible.

If I were to develop a platform-specific workaround, clicking the "Skip button" would give the script permission to close the full-screen, but not to toggle it _(out + in)_. 

I don't see how "click fullscreen twice" vs "click fullscreen once" could solve the problem? 🤔 

The best solution IMO would just be to let the user go "out/in" of fullscreen until Netflix changes something on their platform again, which will actually just replace `src` of the video, instead of the entire element.

**Comment by damooch** [comment]
Because it’s working while full screen but when the next episode plays it
does back to not being ultra wide. However when you make it small then go
full screen again it goes back to ultra wide. It’s not just a Netflix issue
either. It’s an issue on almost every streaming platform where you have to
exit full screen then enter again to get the video to be ultra wide again.

**Comment by damooch** [comment]
I was simply informing you I already wrote my own scripts to fix it for me

**Comment by dvlden** [comment]
Does your solution apply to any video streaming platform?
If so, make a PR of a change and I'll gladly approve it!

**Comment by dvlden** [comment]
Aside, can you let me know where else are you having this issue with "Next episode"? 
I tried Amazon Prime Video and tried YouTube Playlist, but it doesn't have this issue like Netflix.
