### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by talkiestsun0** [dvlden/ultrawideo#36]
I just installed this extension because it seemed like it would be the best one for me, I do not have the extension in pause mode, I have been double-checking that a lot to be sure it isn't paused. And still going to upscale or stretch any youtube video doesn't work, even using my custom shortcut (I don't have a "Meta" key.) toggling through them doesn't do anything, I am still just getting black bars and that is all.

**Comment by PoorPocketsMcNewHold** [comment]
Try setting the video in fullscreen.

**Comment by dvlden** [comment]
I'll assume that you're running a Windows OS. 
The meta key on Windows would be the actual "Windows logo" key... `❖`

As @PoorPocketsMcNewHold said, make sure that your video is in full-screen mode, otherwise, the extension won't do anything to the video.

**Comment by talkiestsun0** [comment]
Yeah I know I've been trying in full screen, if it wasn't I wouldn't be
getting black bars

**Comment by dvlden** [comment]
Right... Well, can you try to allow the extension in incognito mode, then open the incognito and try it out? 
Maybe some other extension is interfering?

**Comment by talkiestsun0** [comment]
sorry for late reply i got busy, but i have no other extensions on my
browser

**Comment by talkiestsun0** [comment]
alright well i just changed it from only being able to view or make changes
on youtube to all sites and it works now, maybe it wasn't allowing it to
change anything because there was a problem with the url or something, I do
appreciate you trying and helping!!

**Comment by dvlden** [comment]
I don't understand how the browser allowed you to manage permissions that extension is asking, but that's definitely interesting to know about. 

Glad you solved the issue yourself and I hope you enjoy using this lightweight, high efficiency – browser extension. ✌️
