### ISSUE TITLE
Support for Firefox Android 79.0.5

### ISSUE THREAD

**Issue by hojjatabdollahi** [dvlden/ultrawideo#37]
### Information
I was happily using this addon in Firefox for Android up until yesterday. The new version of Firefox for Android (79.0.5) broke most of my add-ons. But I desperately need this addon. I was wondering if it is possible to update the addon for this new version. 
Thanks.

**Comment by dvlden** [comment]
Can you tell me a bit more? What has changed?

I never tested this extension for Android, but from the user's feedbacks I heard that it works, so I allowed installation for Android as well and not Desktop only. 

I guess I could install an Android emulator on macOS to test this out, but I'm unsure.

**Comment by dvlden** [comment]
Closing, since no feedback has been given.
