### ISSUE TITLE
Expand only 21:9 video?

### ISSUE THREAD

**Issue by KoborOld** [dvlden/ultrawideo#38]
Hi!

Working with current version of Opera
Can you keep Aspect ratio and only remove the not-needed extra Black bars on 21:9 videos?
Just keep bars on left and right on 16:9 videos on Ultrawide-screens?

Maybe this could be an option in the add-on, as maybe others like to see video in Streched or removed top-bottom part of them.

Thank you,
Kobor

**Comment by dvlden** [comment]
Hello,

This extension uses CSS to manipulate the video. Primary property can be found here:
[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)

It is not possible to do such a thing with this property.

**Comment by KoborOld** [comment]
Yes, that would be good.

The 16:9 (or 4:3) videos will shown as they are, with black bars on sides. (I prefer to see all the details instead of remove some part of the video)
Only 21:9 videos will be shown full screen.

Thank you very much!

**Comment by dvlden** [comment]
Hello again,

After some manual testing, I have found that there are many videos out there with AR of `16:9` that should actually be affected by the extension, as they are rendered to work well for `21:9` screens. 

Example:
[J. Cole – Middle Child](https://www.youtube.com/watch?v=WILNIXZr2oc)

So this option would fail in this case. What do you say about it?

**Comment by KoborOld** [comment]
I have no idea why they put hard coded black bars into videos.
Any chance to crop them and use the real Aspect Ratio? Because They are in fact 21:9 videos....

What I think more is that in a General solution could be to set the Width OR Height of them while the whole video will be 'inside' (not will be invisible, off screen). Possible in that CSS or what you linked me or in your add-on? That would be a really great Solution!

**Comment by dvlden** [comment]
There's no solution to this, unfortunately, because of that side-effect of intentionally added black bars.
However, you gave me an idea for another OSS package that isn't related specifically to browser extensions.

Closing this, until further notice.

**Comment by KoborOld** [comment]
Thank you for looking after it!
