### ISSUE TITLE
Firefox for Android compatibility

### ISSUE THREAD

**Issue by arencambre** [dvlden/ultrawideo#39]
The Fenix release of Firefox for Android was a major revision. Unfortunately, it was a bungled release that wiped out almost the entire add on ecosystem for Firefox Android users. More info on how to become compatible with Firefox Android once again: https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

Not only is Ultrawideo a great and popular plugin, it is an important one to overcome a Firefox Android problem: it scales videos improperly, causing unwanted cropping. More info: https://github.com/mozilla-mobile/fenix/issues/8252. This add on is mentioned as a good solution to the Firefox bug.

(this relates to #37, which was closed due to no feedback from issue author)

**Comment by dvlden** [comment]
Hello @arencambre,

Thanks for the detailed issue. I followed the links you provided to me and ended up here:
[Extension Workshop](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/)

Specifically, this message from the alert box:
> Currently only a limited number of Recommended Extensions are supported. We would like to support more extensions and we are continuously working on how to expand support.

Afterward, I ended up here:
[Recommended Extension Program](https://support.mozilla.org/en-US/kb/recommended-extensions-program?utm_source=extensionworkshop.com&utm_medium=dev-article&utm_content=developing-extensions-for-firefox-for-android)

Now this bit is quite important:
> May I suggest extensions to become Recommended?
> Yes. If there’s an extension you feel should be Recommended, please email amo-featured [at] mozilla [dot] org with a link to its AMO listing page.

So, to my understanding, to have an extension installable on Fenix release, the extension has to be selected by the Mozilla editorial staff as the "Recommended". 

It'd be nice if everyone who's interested in using this extension on Firefox Fenix for Android, to send an e-mail to the one mentioned above. 

Let me know if I misunderstood something?

**Comment by arencambre** [comment]
Looks like this is what you have to do to get it to be a Recommended Extension ([source](https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_may-i-suggest-extensions-to-become-recommended)):
![image](https://user-images.githubusercontent.com/411495/94972652-612ccf00-04cf-11eb-9759-c77a14fdc929.png)

Here's how it can be installed for testing:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by dvlden** [comment]
@arencambre That's basically what I mentioned. 
Can you e-mail them? I already did and some friends of mine. I guess a lot of people need to e-mail them.

**Comment by arencambre** [comment]
I will try. First, I am running on Firefox Nightly for a few days to assure I don't have a problem.

The only issue I notice is I have to switch from **Upscale** mode to **Normal** mode for it to work. If it's on **Upscale** mode, it doesn't help with the cropping.

**Comment by dvlden** [comment]
Are you saying that just by setting to `Normal` mode it does not function? It requires toggle from `Normal` to `Upscale` and back to `Normal` in order to work? 

Or are you saying that just `Normal` mode helps with cropping, but the other two modes do not have functionality?

**Comment by arencambre** [comment]
Apologies, I am saying that **Upscale** is selected by default, and that does not help prevent the cropping. I have to switch to **Normal** to help with cropping. A few days ago, I uninstalled the latest Firefox for Android and went back to version 68 (the pre-Fennec version). I saw the same issue there, too.

For this to be a good idea as a recommended plugin, it needs to prevent cropping in its default configuration.

**Comment by dvlden** [comment]
I see... Hmmm, yeah it does make sense to have `Normal` mode pre-selected by default, but it's kind of the opposite for UltraWide screens, where I think it's preferrable to remain on `Upscale`. 

I'll probably set `Normal` to Android users and `Upscale` to all others. What do you think?

**Comment by dvlden** [comment]
@arencambre I just released v2.2.0, which among some other things sets the `mode` to `normal` for Android users on the initial installation of the extension.

Could you check if this is working? 

• Uninstall extension
• Install extension
• Check if the mode is `Normal` and not `Upscale`

Let me know, I'll be waiting...

**Comment by dvlden** [comment]
Perfect! Let's now just wait until Mozilla decides to add this extension to the "Recommended" ones. 
Until then, I'll keep this issue open.

**Comment by arencambre** [comment]
I just emailed them, too.

**Comment by paceboltz** [comment]
I having a issue on Xiaomi Redimi note 9 pro. camera location side has black bar. 
![Screenshot_2020-12-24-16-24-28-538_org mozilla fenix](https://user-images.githubusercontent.com/76556629/103084245-8d567880-4604-11eb-9026-aeee24289036.jpg)

**Comment by dvlden** [comment]
I just messaged BrowserStack to see if I can get an open-source access there for testing this on mobile devices. 
Thank you for reporting here.

**Comment by dvlden** [comment]
BrowserStack granted my acc with all devices, but I still can't install anything. There's no Play Store. Contacted them back to see what is up with that.

Aside, anyone knows anyone from the FIreFox add-ons team to push this process, into adding UltraWideo to the suggested/recommended installations?

**Comment by dvlden** [comment]
I am closing this issue for now. There's nothing that can be done, until FireFox allows all add-ons to be installed or choose UltraWideo as the extension of their choice - "Recommended".
