### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by sonmiralay** [dvlden/ultrawideo#4]
Chrome Extension dont work anymore

**Comment by dvlden** [comment]
It's funny... One thing that I realized right now is:

- The extension shortcuts never work in production (when you download plugin from the store), but it does always work in development or when you simply manually install the extension without store.

- The extension works fine with basic `<video>` element on the page - in development mode, but it does not seem to be working anywhere else (youtube, vimeo, laracasts)

I'll see what I can do tomorrow. Maybe there's hope...

**Comment by sonmiralay** [comment]
I'm looking forward to. Because there is a single plug-in that runs on all sites on the Ultrawide monitor.

**Comment by dvlden** [comment]
I will be working on complete rewrite of this extension.
Will close the issue when I develop and release new version.

**Comment by dvlden** [comment]
As the rewrite is taking a lot more time than I expected... I have released a bug fix.
The extension is now fully functional again, but the rewrite will eventually come as I already started with it.

Closing the issue as it is now fixed and pushing the extension to all major browser stores.
