### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by dvlden** [dvlden/ultrawideo#41]
It seems that UltraWideo can finally be supported in Safari 14.x and macOS Big Sur. 
However, this will require joining the Apple Developer Program and assign the extension under my company instead.

It will be an expensive addition, for a free open-source extension. Maybe it can become a paid extension on Safari, but then it'd be unfair that it is free on other browsers.

Community, leave your thoughts and opinions. I also wonder how many will become using Safari with the latest coming update?

**Comment by ChrisZeta** [comment]
Yes! I would Pay for UltraWide extension on safari  😍

**Comment by dvlden** [comment]
Note to self:
Following [this guide](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) everything went smoothly. However there are some issues to state, which makes this extension not useful in Safari.

1. The build only has one issue: `persistent` in manifest is not recognized by Safari.
2. Custom shortcuts logic that isn't bound to built-in browser shortcuts, apparently isn't working in Safari.
3. Icons and its states should be differently designed for Safari.
4. Switching between modes manually via pop-up window, doesn't affect played video. Reload after each mode switch is necessary.
5. It apparently makes the video lagging, upon fullscreen switch (in/out).
6. Adding it to the App Store has annual price tag.

Solution?
I haven't thought of any, just yet. Closing, until further notice. 

P.S. If anyone is willing to tackle this issue with Safari, feel free to do so and let me know in this issue if there's any discovery that will be helpful for a quick fix.
