### ISSUE TITLE
Custom stretch ratio

### ISSUE THREAD

**Issue by Heehaaw** [dvlden/ultrawideo#45]
Hello! First things first, thanks for the awesome project! It makes watching video on UW monitors so much more bearable.

Now to the question: 
Would it be possible to enable custom stretch ratios? ie. to be able to input two numbers that represents said ratio in X and Y axes?
This would solve for those random videos with black bars already baked in...

**Comment by dvlden** [comment]
Hello @Heehaaw ,

Thank you for opening new feature request and for using UW. 
Unfortunately that's not possible as the extension doesn't use expensive JS calculations and resize events, it relies strictly on some CSS properties.

Kind regards!

**Comment by Heehaaw** [comment]
@dvlden before I used your awesome extension I always did that manually using CSS3 `transform-scale`... Something like
```css
.uwv {
  &-active &-video &-custom {
    transform: scale(X, Y);
  }
}
```
`X` and `Y` being the custom entered values.

**Comment by dvlden** [comment]
Hmmm, interesting. Does it work well with `object-fit`? 

I'd be grateful if you can test and record 5-10 seconds video.

Thank you in advance!

**Comment by Heehaaw** [comment]
I've [created a fiddle](https://jsfiddle.net/30hv1aqk/)... Try hovering over the images - seems to work OK.

**Comment by dvlden** [comment]
This is very good indeed! How do you think this should be used tho? Two small inputs that allow custom value for X and Y axis, as you stated? 

I am aware that some videos still come with black bars, even after cover or stretch, but it's rare, happens on weird aspect ratios and never happened to me on Ultra Wide screen, only 13" MacBook.

---

Let me ask you a couple of questions, to help myself:

1. How likely do you think this feature would be used? 
2. Do you think that this feature should come with new keystrokes config? _(e.g. `cmd + up/down` to interact with `Y` axis and `cmd + left/right` to interact with `X` axis values.)_
3. If shortcuts are needed, by how much should it increment/decrement? (`0.1`, `0.5` or `1`)

Feel free to discuss with me anything else regarding this feature you have on your mind. It'll just help to develop it as best as possible.

Thanks again!

**Comment by dvlden** [comment]
Also, I'll just say that this might work best if settings were saved per video or at least per platform, as feature request #33 that I did not have time to develop, yet.

**Comment by Heehaaw** [comment]
I always come across some weird videos that are in completely unusable aspect ratios. 
- Filmed on a phone and not properly edited, 
- Screen-casted from an odd source (someone using a projector with 4:3 resolution and videoconferencing it), 
- Letter-boxed videos on sites that are not optimized for ultra-wide (Netflix does that sometimes).

I kinda hate not being able to utilize the whole of my ultra-wide real estate while consuming full-screen content; I can't stand black bars.

That being said, I don't think too many people would use the feature, but some might.

1. As stated above, not many. But those that care enough (like me :-) ) would totally use it.
2. Nice to have, but not required for the feature to be useful. If it is not much work (which I guess is not), why not slap them on.
3. The increments/decrements could be a variable field as well, perhaps?

I'd see the implementation as a 4th toggle, which would expand a sub-menu with 2-3 inputs (or sliders, or both) - `X` scale factor, `Y` scale factor and optionally a scale step input.
What do you think?

> Also, I'll just say that this might work best if settings were saved per video or at least per platform, as feature request #33 that I did not have time to develop, yet.

This would be nice indeed. But not crucial for custom scaling to be useful, I think.

**Comment by dvlden** [comment]
Very descriptive and useful. 
I like the variable field thought for the increment/descrement.

Would this feature be something that you would be willing to contribute to the extension yourself?

I am busy with a paid project until the end of February and I'm not certain that I'll get spare time after that period. But I really hope so!

However, if not you, someone else might be willing to jump into this feature?

Thank you for the suggestion @Heehaaw !

**Comment by Heehaaw** [comment]
I don't have much time myself. At least not right now. I might be able to slip in a couple of hours here and there, but nothing certain, nor regular. We will see...

Thanks for the awesome extension!

**Comment by metasikander** [comment]
Missing this feature myself, since i have a 50" screen and "the mandalorean" is either in letterbox or cropped (with ultrawideo upscale).
Unfortunately not a dev myself, but if there is anything else i can do to help make this happen, just let me know!
