### ISSUE TITLE
Not working properly on 32:9 Monitors (Disney+ and Netflix)

### ISSUE THREAD

**Issue by mcmodderHD** [dvlden/ultrawideo#48]
### Describe the bug
No feature fits to a 32:9 Monitor. 

### Reproduction steps
Trying out every option on a 32:9 Monitor on Disney+/Netflix

### Expected behavior
One of the features should remove the black bars without stretching or cutting of parts of the video

### Environment
- **OS**: Windows 10
- **Browser**: Mozilla Firefox (85.0)

**Comment by dvlden** [comment]
Hello @mcmodderHD ,

My monitor is 34" 21:9 and the only time I get great video without any cut parts and no blackbars is when the video is intentionally rendered to have black bars on all sides. I don't have an example right now, but if I stumble upon one soon, I'll update this comment.

What you're asking for is not possible. 
You can enjoy either with cut-off parts or with stretched parts.
