### ISSUE TITLE
Not working on Macbook/Chrome

### ISSUE THREAD

**Issue by mfoufoutis** [dvlden/ultrawideo#5]
### Describe the bug
Extension doesnt seem to have any effect on videos. I tested it on youtube as well as other video sites.

### Reproduction steps
Open page with video. 
start video.
click on addon.
toggle any option.
no change on video

tested with and without adblock running

### Expected behavior
expected behaviour: video should change aspect/ quality

### Environment
- macOS v10.14.3
- macbook Pro 15" (2015)
- Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by mfoufoutis** [comment]
Ps installed via chrome store 
https://chrome.google.com/webstore/detail/ultrawideo/bfbnagnphiehemkdgmmficmjfddgfhpl/related?ref=producthunt

**Comment by dvlden** [comment]
Hello @mfoufoutis,

From what you're saying, sounds to me like you are not using the extension the way it is created to work. 

The video player must go to fullscreen...

**Comment by mfoufoutis** [comment]
Hi @dvlden Dvlden

thats what i thought. thanks for the clarification
