### ISSUE TITLE
Doesn't seem to work for Amazon Prime Video

### ISSUE THREAD

**Issue by XDracam** [dvlden/ultrawideo#53]
### Describe the bug

Extension does nothing on Amazon Prime Video, particularly on Doom Patrol s2e1. To be fair, no other extension I tried worked either.

### Reproduction steps

If you can get access, open Doom Patrol s2e1 on Amazon Prime Video. No button in the extension does anything. Reloading doesn't work either.

I'd love to give you access, but I will not share my amazon account data for obvious reasons. Sorry 😅

### Environment
- **OS**: Windows 10
- **Browser**: Chrome 91

**Comment by dvlden** [comment]
@XDracam It's unfortunate, but the only account I have for Amazon Prime is my sis' account. She's from Germany, so here's the SS.

If you cannot send me an email with your credentials to do the debugging, there's nothing I can do, sorry.

![Screen Shot 2021-07-11 at 22 20 33](https://user-images.githubusercontent.com/3460368/125209016-542ae080-e296-11eb-817d-cd6d7b224362.png)

**Comment by dvlden** [comment]
I'll install TunnelBear now to make sure it doesn't interfere with my location (Serbia).

**Comment by dvlden** [comment]
I just want to post an update regarding this. I used TunnelBear (Germany) and show worked. Aside, the extension is also working just fine. I've been using Chrome for most of my life, but made a switch to FireFox. 

Nevertheless if it works in FF, should work in Chrome as well.

https://user-images.githubusercontent.com/3460368/125209254-de277900-e297-11eb-80c9-5e4fd6bc9853.mp4

I am showing in this video that extension is fully working in full-screen for the specified show and I'm toggling between modes with shortcuts.
