### ISSUE TITLE
Not working on MUBI

### ISSUE THREAD

**Issue by jmeintrup** [dvlden/ultrawideo#54]
## Before opening
Found no duplicate for Mubi

> ## IMPORTANT!
> If this bug report is regarding the extension not functioning on a specific platform, please e-mail me the platform link and your credentials to `n.dvlden@gmail.com`. Many video streaming platforms/VOD platforms are paid and I don't have access to all of them. When I'm done with solving the issue, just change your password and be done with it.

You can create a free trial, but if not possible i please tell me so.

##
Plugin not working on MUBI

### Reproduction steps
Simply view any video on MUBI

### Expected behavior
The video can not be cropped or scaled in any way on the MUBI platform.

###
I believe they are using a non-standard HTML5 player on their site, i'm not sure.

### Environment
- **OS**: Win10
- **Browser**: Version 1.28.106 Chromium

I tried Firefox as well, no difference.

Plugin is v2.4.2

**Comment by dvlden** [comment]
It's been 14 days. No response from @jmeintrup and no issues on my end, so I'm closing this issue.
