### ISSUE TITLE
Extension on chrome store not available

### ISSUE THREAD

**Issue by Cocobnan** [dvlden/ultrawideo#65]
## Before opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

## IMPORTANT!
If this bug report is regarding the extension not functioning on a specific platform, please e-mail me the platform link and your credentials to `n.dvlden@gmail.com`. Many video streaming platforms/VOD platforms are paid and I don't have access to all of them. When I'm done with solving the issue, just change your password and be done with it.

### Describe the bug
A clear and concise description of what the bug is... _(remove this sentence)_

### Reproduction steps
Steps to reproduce the behavior... _(remove this sentence)_

### Expected behavior
A clear and concise description of what you expected to happen... _(remove this sentence)_

### Environment
- **OS**: [e.g. macOS v10.14.3]
- **Browser**: [e.g. Chrome v72.0.3626.109]

**Comment by dvlden** [comment]
I have contacted Google Chrome Developers team regarding this inquiry. I closed my Google Workspace account with them and they terminated my Developer account along with it. 

Long story short, I'm waiting for them to restore my account. I contacted them on 24th and I'm still waiting...

**Comment by dvlden** [comment]
I'll keep this open, in case others wonder.

**Comment by Cocobnan** [comment]
Any news? Isn't better to do a new account or use another account to upload the extension ?

**Comment by dvlden** [comment]
Yes. Received news today… They are unable to restore my account for some reason, but they will attempt to transfer ownership to my secondary e-mail… 

This may take some time, and I’m really hoping it’s possible.

Uploading on a new acc would lead to another id and losing all stats.

**Comment by dvlden** [comment]
The extension was transfered to my secondary account today. I had to refill all of the extension information and reupload the images. After their review, it should be published again and available under same name and id. 

I'll close the issue when extension is approved by Chrome team.

**Comment by dvlden** [comment]
@Cocobnan The extension has been sucessfully restored. You may install it from Chrome Web Store now as usually.
