### ISSUE TITLE
this extension is garbage, and does nothing. just delete it from firefox extensions market

### ISSUE THREAD

**Issue by NeverBeLazyG** [dvlden/ultrawideo#67]
## Before opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

## IMPORTANT!
If this bug report is regarding the extension not functioning on a specific platform, please e-mail me the platform link and your credentials to `n.dvlden@gmail.com`. Many video streaming platforms/VOD platforms are paid and I don't have access to all of them. When I'm done with solving the issue, just change your password and be done with it.

### Describe the bug
A clear and concise description of what the bug is... _(remove this sentence)_

### Reproduction steps
Steps to reproduce the behavior... _(remove this sentence)_

### Expected behavior
A clear and concise description of what you expected to happen... _(remove this sentence)_

### Environment
- **OS**: [e.g. macOS v10.14.3]
- **Browser**: [e.g. Chrome v72.0.3626.109]

**Comment by dvlden** [comment]
I'm sorry, but the extension is working properly. I'm using FireFox myself for all sorts of things... 
The extension is working as expected. If you had different expectations than what it already does, sorry about that.
