### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by ViktorOn** [dvlden/ultrawideo#68]
I would like to add a translation into Russian. If you have time, I will help.

**Comment by dvlden** [comment]
I always wanted to implement i18n in the extension. I tried once and rather quickly realized that it's not possible, with current implementation. 

Not sure what it was exactly at this point. It's been a while. 
Have you tried to implement Russian translation in it?

This would be nice for sure!

**Comment by dvlden** [comment]
All popup data is located at `src/pug/data.js` and as far as I know, we can't use `browser` api, outside of the extension itself, can we?

**Comment by ViktorOn** [comment]
> I always wanted to implement i18n in the extension. I tried once and rather quickly realized that it's not possible, with current implementation.
> 
> Not sure what it was exactly at this point. It's been a while. Have you tried to implement Russian translation in it?
> 
> This would be nice for sure!

I translated in my fork, but manually installing the extension did not work (Error Manifest file is missing or unreadable)

**Comment by dvlden** [comment]
That's all good. You just need to build the extension and install it from the packed file or `dist` output. 
However, your fork is not internationalized, it's just replaces English strings to Russian. I don't think it's possible for me to implement current browsers i18n api, at least I don't know how to.

**Comment by ViktorOn** [comment]
> All popup data is located at `src/pug/data.js` and as far as I know, we can't use `browser` api, outside of the extension itself, can we?

I'm not an assistant here.

> That's all good. You just need to build the extension and install it from the packed file or `dist` output. However, your fork is not internationalized, it's just replaces English strings to Russian. I don't think it's possible for me to implement current browsers i18n api, at least I don't know how to.

If we talk about the possibilities, it seems to me they are there, but I do not know them.
