### ISSUE TITLE
Option for toggling between only 2 modes

### ISSUE THREAD

**Issue by MrTheRich** [dvlden/ultrawideo#7]
It would be great if there was an option so there could be switched between only 2 modes instead of all 3. 

So that when the hotkey is pressed it switches between upscale and normal and skips stretch, for if you never use that option.

**Comment by dvlden** [comment]
Hello, @MrTheRich.

That would have to be yet another configuration.

> Select at least two modes that you plan to toggle between...

This doesn't sound like a feature that everybody could take advantage of and it'd add another layer of complexity to maintain.

I highly suggest you to clone this repository and try to implement that yourself and then load it from your local drive into the browser as extension. 

Thank you for your suggestion and time, but this is not something that I would personally want to implement.

**Comment by MrTheRich** [comment]
`it'd add another layer of complexity to maintain.`
why not make use of the build in extension options for chrome for advanced settings. so the pop up settings window can stay simple?

**Comment by dvlden** [comment]
Care to explain? I don't follow...

**Comment by MrTheRich** [comment]
When right clicking on an add-on icon in the top right of the chrome window. There is an [Options] menu entry, it's there for all add-ons, but it's grayed out for apps that don't make use of it. Most apps that use it link to some back end settings menu for advanced settings.

**Comment by dvlden** [comment]
The logic to handle that still ends up in the bundled code and it'll be hard to maintain it.
