### ISSUE TITLE
Upscale by percentage

### ISSUE THREAD

**Issue by Sopor** [dvlden/ultrawideo#71]
### Information
I have two requests...

1. Let me exclude sites i don't want to upscale or stretch.

2. When using upscale there should be a percentage on how much i want to upscale it. When i run Kodi i never upscale it to fill the whole screen because it will make it cut too much at the top and bottom. I use 1:24 and leave a small black bar at the side.
This should be possible to do in Ultrawideo too.

**Comment by dvlden** [comment]
Both of these features have already been requested. You may check the [Discussion](https://github.com/dvlden/ultrawideo/discussions) for more.
I do have plans for them but in v3. 

If you can and would like to contribute these in v2, feel free to make a PR. 

Best regards!
