### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by rgiotxy** [dvlden/ultrawideo#75]
## Before opening
> [Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

Doing this shows that this issue may either be the result of the recent update to 2.5.0 or be resolved by updating to 2.5.1 (or both); if so, **how do I either downgrade to the version immediately before 2.5.0 or update to 2.5.1?**

## IMPORTANT!
>If this bug report is regarding the extension not functioning on a specific platform, please e-mail me the platform link and your credentials to `n.dvlden@gmail.com`. Many video streaming platforms/VOD platforms are paid and I don't have access to all of them. When I'm done with solving the issue, just change your password and be done with it.

I initially thought it was limited to Vidcloud, but I've since realised it is also occurring on every other platform (e.g. MyCloud).

### Describe the bug
>A clear and concise description of what the bug is: 

I normally use this extension to watch full videos in full screen, since, for some reason, attempting to do so without the extension causes the video to be cropped, allowing me to watch just a part of the video in full screen. In some videos, the area cropped if my screen orientation is horizontal is minimal, while in others it is very significant and the video becomes impossible to watch; in any video, attempting to toggle full screen while in portrait orientation causes the vast majority of the video area to be cropped out (only always so laterally, while in landscape orientation the cropping is always on the top and/or on the bottom instead). I hadn't had this problem since I first installed your extension two years ago, but suddenly, today, it came back, as though the extension has stopped working entirely.

**EDIT**: in YouTube it appears to be making the videos small and centralised instead of cropping them like the absence of the extension would (although, pausing the extension does not revert to expected cropping behaviour, so maybe this is the new equivalent to the extension not working on YouTube). This bug has also been reported in some now-closed threads, so it's probably the same.

### Reproduction steps
>Steps to reproduce the behavior: 

I don't know. Maybe you'd need a Samsung Galaxy A51 or similar device first. In any case, install Firefox for Android 68; install UltraWideo browser extension; set UltraWideo to "normal"; attempt to watch any video in full screen and see if it's working (e.g. in VidCloud or MyCloud, working = video displays correctly, not working = the video is cropped; in YouTube, working = video displays correctly, not working = video is either cropped or may seem small and centralised), i.e. if the result of toggling the video full screen is any different depending on whether UltraWideo is on / not paused or off / paused.

### Expected behavior
>A clear and concise description of what you expected to happen: 

The video should look identical to what it looks like when not in full screen, except in full screen so I can enjoy the full size of my screen instead of having to watch a tiny video in order to see it whole (=uncropped).

### Environment
- **OS**: Android 10 (Samsung Galaxy A51, native ROM)
- **Browser**: Firefox for Android 68.9.0
- **Extension**: UltraWideo 2.5.0

**Comment by rgiotxy** [comment]
Update: **issue completely resolved with seemingly automatic update to UltraWideo 2.5.1**, as implied by other recent threads that were already closed when this one was being opened. I'm closing it now, as the issue is functionally resolved, but I would still like to know, if possible
(1) Why did I update automatically to an already deprecated update that was known to be problematic if a newer and improved update was already available? I mean, by the time I was automatically updated to 2.5.0 and reported it not working, people were already reporting the same issue fixed with update 2.5.1, so why did I not just skip 2.5.0 entirely and jump straight to 2.5.1?
(2) Is there a way I could have prevented this? For instance, by updating manually to 2.5.1 when the issue first appeared to me and the solution was already available, or by preventing the update to 2.5.0 entirely and waiting until 2.5.1 became available to jump straight to it?

**Comment by dvlden** [comment]
Hey, thanks for reporting the problem. 
I'm happy that this is resolved in 2.5.1. 

I am honestly not sure how Chrome's or Firefox's web store works and how they pass the updates to the users. Two releases were happening on the same day I think, so you might have received the update later than some other users.

Don't think there's anything you could do, except visit the browser addon store and see if there's a newer version than you have installed in your browser and then you could uninstall the extension and install the latest one. But this shouldn't be something to worry about. Just wait for auto-update and you'll eventually get it. 

Best of luck!

**Comment by rgiotxy** [comment]
Thank you =)
