### ISSUE TITLE
Add instructions to help section 

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#76]
Hello, I use Ungoogled-Chromium and chromium browser and i love Thorium browser ......but Ultrawideo doesn't support officially these browsers, and the extension doesn't work with these browsers, it will be great confortable useful for ordinary uses to add these instrcution in FAQ and the descriptin of the extension in github page because that may help users to fix the problems in not supportend browsers.....tahnk you for this awesome extension that sould be integrated by default in every web browser  :)

Approach 1
Run the browser with a specific flag.

Quit the browser
Right click on the browser's shortcut and go to Properties
Within the Target box, add --disable-direct-composition-video-overlays` to the end (outside of quotation mark) and apply the changes
Launch the browser
Approach 2
Change graphics back-end for ANGLE.

Launch the browser
Open browser://flags/ (replace word browser, with the one you're using, e.g. chrome://flags/)
Search for ANGLE (full option name: Choose ANGLE graphics backend)
Choose D3D9 or OpenGL
Restart the browser
Approach 3
Disable hardware acceleration.

Launch the browser
Go to browser settings
Search for hardware (full option name: Use hardware acceleration when available)

**Comment by dvlden** [comment]
Hey, 

By not working, you are saying that the browser config needs to be modified?
Or are you saying it's not installable or something?

This guide can be found in Discussion(s) and it's pinned, but here's the reference:
https://github.com/dvlden/ultrawideo/discussions/62

Are you saying that I should add this guide in the "welcome" screen (post-installation of the extension)?

**Comment by dvlden** [comment]
I will keep this open as a reference for what I need to do.
Thanks!

**Comment by trimechee** [comment]
Wonderful ! Thank you so much :)

**Comment by dvlden** [comment]
New onboarding for v3 has arrived.
I did not implement this specific OS bug fix, but I will. 

Adding it to the notes now and will think of a good way to mention it as very important and link to the discussion board.
