### ISSUE TITLE
Suggestion: For clarity, rename "Toggle Pause" to "Pause Extension" and "Toggle Modes" to "Switch Mode"

### ISSUE THREAD

**Issue by martinsstuff** [dvlden/ultrawideo#77]
Re: #17 #20

I usually expect a toggle to be a binary switch, right now both keybindings "Toggle Pause" and "Toggle Modes" are not binary switches, and in particular with the "Toggle Pause" keybind, I initially thought its behavior was a bug due to that description.

My proposal is to rename "Toggle Pause" to "Pause Extension", this would make it clearer that it's a one-way operation and also explain why the keybind no longer works once triggered (the extension is, well, paused).

I also propose renaming "Toggle Modes" to "Switch Mode", while "toggle" isn't too out of place here, I believe using "switch" would be more fitting as it "switches through" different modes. "Rotate Mode" would also work.

**Edit:** Changed "Mode**s**" to "Mode", since it's not a group of modes that is being selected, but a single mode.

**Comment by dvlden** [comment]
Sure thing. I think I did it exactly as you described. 
Let me know if that's what you meant.

**Comment by martinsstuff** [comment]
Thanks for implementing my suggestion, everything looks great on my end 👍
