### ISSUE TITLE
Add a black or whitelist feature

### ISSUE THREAD

**Issue by cratermaddie** [dvlden/ultrawideo#78]
Hello, There are certain sites that don't always look ideal with the content changed. Rather than having to pause and un-pause the extension whenever we navigated to these pages it would be great to have a blacklist or something to add sites to if we don't want them effected.

**Comment by dvlden** [comment]
Hello,

Thank you for opening up a feature request. I have moved these into Discussion, and this specific one has already been discussed here #70 ...

I have heavily planned a new v3 but did not have time for it yet. 

If you wish to contribute to existing source code with this specific feature, go ahead, I really dig it.
