### ISSUE TITLE
No stretch or upscale in streaming site

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#79]
Hello, our beloved Ultrawideo doesn't work in my prefered streaming site , i have last version of firefox and Ultrawideo,  when i choose the first link of media player (EVO TV) , the extension doesn't stretch or upscale the video , t tried to disable hardware acceleration but the bug persist : 

https://wiflix.bet/serie-en-streaming/23805-halo-s-1.html

**Comment by dvlden** [comment]
Hello,

I am not quite sure I follow and understand the issue. So please explain it to me if I'm wrong.
I tried to play the video from the link you sent, and the modes work.

If you are referring to subtitles being cut out, that's because they are not external subtitles as they are supposed to be, but instead directly added to the video and exported.

https://user-images.githubusercontent.com/3460368/181589692-05e40b36-87cd-43f8-9b82-256e772db8fc.mp4

**Comment by trimechee** [comment]
I have black bands at the top and bottom of the video when I play the videos from this site, I used firefox with disk cache disabled and hardware acceleration disabled and I used chromium with hardware acceleration disabled and I I activated the D3D9 flag and I still get the black bands at the top and bottom of the video, I did not encounter this bug before, I delayed the update of windows 10, is it an update problem? day maybe? I recently changed the default values of intel graphics..... I will try with edge browser

**Comment by dvlden** [comment]
Hmmm... I honestly have no ideas. 

When issues with Windows arised, I really wanted to remove the extension from the market. 
Luckily there were these necessary work-arounds from the Guides but still not fun.

Does it work elsewhere?

**Comment by trimechee** [comment]
I finally found the reason for the bug!!!  it's very strange !!!

I defaulted the intel graphics values, deleted the extension, reinstalled, deleted the cookie cache....but the bug persists even on edge browser....but I remembered something while watching the video that you posted, you clicked on the link of the video in English vostfr, and I watched the video in French vf !!!

when I clicked on the links of the videos in English vostfr, the extension works perfectly, but strangely, when I watch the videos in French language vf, the extension Ultrawideo does not work anymore!

please try to click on the "VF" links on the right which are in French vf, very strangely the extension no longer works with french vf videos unlike the English vostfr videos, it's very strange and bizarre bug !!

**Comment by trimechee** [comment]
and of course we hope you won't delete this magnificent and essential extension from the chrome and firefox store please!

It's noraml and banal that bugs happen given the updates of browsers or media players and there is no problem:) Ultrawideo works with many other sites, thank you very much and we hope that Ultrawideo will not be deleted!

**Comment by dvlden** [comment]
Here's another video recording. Did I do it right this time? 
I tried one link from both lists, and both seem to work fine over here. 🤷‍♂️

https://user-images.githubusercontent.com/3460368/181656185-ee6b08ab-4848-4922-b14f-2ab8978daf68.mp4

**Comment by trimechee** [comment]
No, you have clicked on the wrong video, you shouldn't see the subtitles in the video, the vostfr videos with subtitles work well with me without bugs, the bug is in the French "VF" videos without subtitles , please look carefully on the right side, there are links of the video with the title "VF", try to click on one of these video links on the right, just to the right of the vostfr links, under each video, there are two sections: section "VOSTFR" and section "VF", the bug is in the video links  of section "VF" without subtitles

**Comment by trimechee** [comment]
Sorry, i see that you have click on the links of VF videos, may be i have change some chrome flags or firefox flags, or may be windows 10 has to be updated, i I'll try to check, thanks for your help :)

**Comment by trimechee** [comment]
I forgot to say that I activated a lot of shortcut keys recently, for example keys to move the mouse cursor with the keyboard keys, I activated the sticky keys .....

**Comment by trimechee** [comment]
I'm trying to make my laptop faster by disabling background services to disable microsoft store, I made a bat script to stop these services:

net stop LicenseManager
net stop InstallService


I'll try to restart the pc and not disable these services and see if the bug persists, it's really weird that the video on the same EVO TV platform, in English the extension works but if the video is in French, the extension doesn't work, i will try to enable vulkan graphic backend in chrome flags.....

**Comment by trimechee** [comment]
Hello, i have disabled virtualisation and Intel VT....in bios setting, it may be the cause of this bug ? it's surprising that the extension works on videos and does not work on other videos of the same video platform ..... I think I will uninstall the graphics card and reinstall in sha Allah

**Comment by dvlden** [comment]
I have no clues what could be the cause. 🤷‍♂️

**Comment by trimechee** [comment]
There is no problem, thank you very much ! i have tweaked many settings of windows, browsers...may be this cause this bug....temporarly, i use "chrome://media-internals/" to find the url of the streaming video and copy the url to "Potplayer" media player that stretch the video and as a bonus, I can buffer fill video with potplayer....or i use the open source extension
 
https://github.com/rowrawer/stream-detector/

to find url video and paste it to video player that stretch the video like vlc.....it's not as fast as watching directly in the browser but that's ok lol :)

**Comment by trimechee** [comment]
i forget to say that i have disabled the 5 intel services with "msconfig", i enbaled them but may be i have installed chromium or firefox with intel services disabled and that cause this problem...
