### ISSUE TITLE
Manuel stretch crop zoom without auto-detection

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#80]
Hello, since there are often updates in web browsers and video players and to avoid any possible bugs, I suggest to our favorite extension Ultrawideo to add a manual selection so that the user can increase itself the height and width of the video : 
for example, the user puts the height and width values himself : 
X-Scale (width):
1
Y Scale (height)
1.33

this mode will disable automatic auto detection which can have bugs and the user himself by setting the values for cropping, stretching, zooming..... the user will set him self the aspect ratio and can overwrite the default width/height scale of the player and overwrites the CSS selector transform:scale(x,y) to crop, stretch zoom the video and increase size of the video, it will be nice to add some kind of button on the video and then, the user himself will increase or decrease manually the height and width of the video, thank you very much !

**Comment by dvlden** [comment]
Thanks for raising an issue regarding the new feature. 
I have moved these to the Discussions page, as it's more suitable.

Already discussed here #60 💯

**Comment by trimechee** [comment]
Great ! thank you very much :) i discover that windows update give me driver of graphic card dated of 2020, but i disvocer aloso on the the page of driver donwloads of Asus that there is new driver of graphic card dated of december 2021, i will try ton instal the new driver and update windows 10 to last version and see if the extension works in sha Allah !
