### ISSUE TITLE
Android Smartphone Video Streching works partially

### ISSUE THREAD

**Issue by downtoground** [dvlden/ultrawideo#81]
Im running this extension on my Android LOS19. The Kiwi Browser is able to run Extensions.

The Extension works out of the box, but the mode "Streching" wont use the whole screen over the camera.

This Extension works better: https://chrome.google.com/webstore/detail/zoom-to-fill-ultrawide-vi/adpjimagbfpknkodpofjphpbdlfkeiho
but has no gestures!

Hope for a Fix! Thanks a lot

**Comment by downtoground** [comment]
Push ;-)

**Comment by dvlden** [comment]
Screenshots and video recordings are appreciated. I do not have an Android and the extension is made primarily for desktop use, but I can try to debug through an emulator.

**Comment by R0M4N0F5K7** [comment]
Nah the full screen mode of the mobile browser seems to be confined to the area under the display cutout just as the any other view of the browser. I think the app makers have to support this (i.e. the browsers in our case would have to overwrite the display cutout areas when going fullscreen). It seems to me that the reason why this obvious thing doesn't seem to be implemented in all mobile browsers is that some versions of andoid (Huawei, maybe Samsung?) have implemented workounds on their OS level that detect fullscreen attempts or even let users hide the display cutout manually via gestures. With that some browser developers don't see the need to act themselves as it does work for some users.

There might be a hacky way to work around that, but I get the notion that it might not be work the effort for this addon all things considered.

**Comment by dvlden** [comment]
Okay, that's about right then. 
I was thinking if fullscreen video in the browser actually takes all that space, then it would be a bug with the extension.

Thanks for your research and time!
