### ISSUE TITLE
5120x1440 Resolution YT Videos cut off top and bottom

### ISSUE THREAD

**Issue by holycow131415** [dvlden/ultrawideo#82]
Hello,

Just tried your extension on youtube. The videos are really cropped top and bottom of the videos at my resolution on upscale mode. Are you able to support this resolution? It would be cool!

**Comment by dvlden** [comment]
Hello,

I'm sorry, but that aspect ratio is too big for any video output to be perfect.
It's just impossible to develop any changes that would be an excellent fit for this comprehensive resolution with a very short vertical.

**Comment by VR-Nima** [comment]
Hi @dvlden, I hope you reconsider. A scaled-to-fit option, even if not pixel-perfect, would be ideal for use on Samsung Neo G9. If this was supported on FireFox, I'd donate to your app. As it is, I have to use a different plugin in a different browser for my monitor instead.

**Comment by dakotahawkins** [comment]
@dvlden I need this too :(

Lots of streaming videos are encoded at 16:9 but have most of their content in a shorter/wider ratio, giving us black bars on the top and bottom as well as on the sides. It's really annoying :(
