### ISSUE TITLE
Vertical videos don't behave well

### ISSUE THREAD

**Issue by francislavoie** [dvlden/ultrawideo#85]
### Describe the bug
This is on the Upscale mode.

For example https://www.reddit.com/r/interestingasfuck/comments/x7nftw/unusual_cube_shaped_cloud_seen_in_the_uk/ it ends up stretching the vertical video to the full width of the display, which means I only see like the top 1/3 of the video. Kinda sucks.

Also tangentially, I have two monitors, a 21:9 and a 16:9. If I fullscreen a video on my 16:9 that is wider than that, e.g. an 18:9 youtube video for example https://www.youtube.com/watch?v=m53_jtJR-Ig, it ends up cutting off some of the sides.

### Reproduction steps
(see above)

### Expected behavior
Videos shouldn't stretch past the edges of the screen.

### Environment
- **Ubuntu Linux (same behaviour on Windows)**
- **Firefox v104**

**Comment by dvlden** [comment]
Everything you have just described sounds like the extension is working as expected.
Yes, vertical videos will be stretched or upscaled if you select these modes, select Normal mode if you don't want them affected.

**Comment by francislavoie** [comment]
Is there not a way to detect the actual height of the video, and cap the scaling to its height? Doesn't feel like upscaling to shift most of the video off the screen makes much sense. Especially on websites (like Reddit) where you don't really know from one video to the next whether it'll be vertical or horizontal.
