### ISSUE TITLE
Version for Pale Moon Browser and Basilisk Browser

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#87]
Hello, I recently installed palemoon browser and I discovered some options not present in mainstream browsers, for example I can disable MSE media source extension and buffer full video in some streaming websites, and it use less memory... .

I spoke with the palemoon team about suggestions and improvements but i get a little argument with one of the maintainers when I said something about ad blockers  lol.....and I was banned from the forum for a few days lol, so I don't like to make my request to their forum anymore, that's why I'm posting my request here, it will be great if our beloved Ultrawideo adds an extension for pale moon, there is a manager in charge of adapting firefox addons for palemonn but unfortunately I no longer wish to express myself in the palemoon forum after this misunderstanding.....

Thanks a lot :)

https://forum.palemoon.org/

**Comment by dvlden** [comment]
Hello,

I know nothing about this browser, and it also isn't available for macOS. 
I'm trying to keep the extension on the two stores necessary, Chrome and Firefox.

Since all of the WebKit browsers are allowing installation from the Chrome web store. 
The only piece missing is Safari, but their eco-system for add-ons is F'd up, so I'm also avoiding Safari as an option.

You said something about "the manager adapting the firefox addons for their browser," so I'll assume it just works if it's made as a cross-browser extension, no?

I'll leave this open if many people use PaleMoon and want UW on it.

**Comment by trimechee** [comment]
Great ! thank you :) and there is no problem, it's just a suggestion, the idea is to let pale moon team adapt stream detector like extension down them all, and may be you may give them some technical advice or expertise.....i understand, there is no problem :)  the only problem is that i don't like to write again in the forum and thank you again for this wonderful extension 🥇 

because of what happened, unfortunately I had a fight with the manager of the "extension addons" part of pale moon, he made a fork of the famous extension down them all to pale moon, the developer and manager of the extensions is moon bat,


https://gitlab.com/xul-extensions/getemall

https://forum.palemoon.org/viewtopic.php?f=46&t=26577

in fact, the idea is to use pale moon to play video streaming when my connection becomes very weak because pale moon has an option to quickly disable the MSE media source extension so I can buffer full video until the end and avoid stuttering But a lot of videos don't occupy full screen that's why an extension like Ultrawideo is essential.....i don't know, maybe i would have the courage to connect to the forum and reconcile myself with moon bat and ask him to include Ultrawideo in the pale moon store ..... in any case thank you very much for your kindness and precious help and for this magnificent essential extension 💯

**Comment by trimechee** [comment]
Here dodumentation about addons support : 

Build targets
Pale Moon (and the Unified XUL Platform) can be built for many systems. While the process is similar across the board, each target operating system or processor architecture has its own specifics.

http://developer.palemoon.org/build/



Add-ons: Overview
Add-ons are a hallmark of classical mozilla-style applications and as such a lot of this information not only applies to Pale Moon but to [Basilisk](http://www.basilisk-browser.org/) and other applications based on the Unified XUL Platform.

Add-on concepts
There are many concepts when it comes to the add-on technology employed in UXP and used by Pale Moon. As such, there is an on-going effort to (re-)document them and you will see them here soon. You may also find valuable information under External Resources in the site's menu bar.


http://developer.palemoon.org/addons/

**Comment by trimechee** [comment]
I mean even if MSE media source extension is enabled, we can even though full buffer the streaming video in palemoon browser and basilisk browser !! 

and it is easy to go to "about:config" and  disable or space out the intervals of session store that consumes energy and tires the hard disk with many write operations .....beacause session store can use 25Gb of write operations in a single day in 2016 according to a study ! maybe it changed In 2023 and session store use less data but the session store still not good for ssd...

i don't disable MSE any more beacause some video streaming players does'nt work if MSE is disabled....

**Comment by trimechee** [comment]
I have just redone tests on this site with the new version of palemoon and this site offers several video players for the same video, and by disabling the mse in palemoon, several video players have full buffer the video with mse disabled in particular uqload and ok .ru and others!
it's breathtaking!

https://v5.voiranime.com/anime/dragon-ball-z-vf/dragon-ball-z-255-vf/


but when i tried my sensational discovery in firefox, it doesn't work, even disabling the mse, i can't full buffer the video in firefox, so palemoon becomes the most powerful and useful and revolutionary web browser in the world and we are not obliged to subscribe to expensive internet packages and we hope that there will be a version of our beloved Ultrawido for palemoon and basilisk browser especially since there are very important and structural updates in the future in sha Allah !

**Comment by trimechee** [comment]
Hello, there is "moonbat": the addons manager in palemoon who is responsible for making firefox addons compatible with palemoon: "forked from their original Firefox as well as brand new ones targeted towards the Unified XUL Platform that carries onward with XUL/XPCOM technologies abandoned by Mozilla in 2017 for being 'obsolete'.



the only problem is that i argued with moonbat when i talked about ad blocking manifest v3 lol......

so I can't ask moonbat to make Ultrawideo compatible with Palemmon, I don't know if the great Mr @dvlden  has the time and the great generosity to talk to moonbat telling him that if he wants to make palemoon beautiful with our beloved Ultrawideo, Mr @dvlden could maybe help him or give him some advices or technical assistance to make Ultrawideo compatible with palemoon....

I don't think I can make a new account on the palemonn forum because they detect my ip address...I was even accused of being a former user who argued with them in the past when it's wrong lol!


https://forum.palemoon.org/viewtopic.php?f=46&t=26577


for example moonbat managed to fork the famous extension downthemall:
https://addons.palemoon.org/addon/getemall/

**Comment by dvlden** [comment]
I tried Palemoon, thinking it could install Firefox extensions, but it can't. 
Unfortunately, converting output from zip to xpi, doesn't work either. Says: "Palemoon does not support WebExtensions". 

Unfortunately, this won't be happening in that case.
