### ISSUE TITLE
Binge.com.au not correctly supported

### ISSUE THREAD

**Issue by peter-wake** [dvlden/ultrawideo#90]
When viewing "Binge" (binge.com.au) service on PC - Windows 10 - latest Chrome browser, the image is incorrectly scaled, clipped and mispositioned so that most is off the top of the screen and clipped left and right.

Styling applied by Binge in outer elements is interfering with Ultrawideo (and other tools') attempts to scale to fullscreen. It's overlaying black boxes left and right to do letterboxing, and doing something contrived with positioning too.

The "zoom to fill" tool correctly scales, but is still clipped, rendering the scaling useless.

See this guide to how Binge can be remediated manually: www.youtube.com/watch?v=DdUdny4nfxs

I believe Binge offers a two-week free trial, so credentials not necessary to test.

**Comment by dvlden** [comment]
I am sorry. Tried my best to sign up, but by entering fake phone number, it asks me for mobile verification, which I cannot provide. 

If you can provide me with the credentials through my e-mail, I'll happily look at this issue and solve it.

**Comment by dvlden** [comment]
Closed due to no response.
