### ISSUE TITLE
custom resolution

### ISSUE THREAD

**Issue by aeneas01** [dvlden/ultrawideo#93]
love your extension, but for some reason the stretch option doesn't play well with my custom widescreen resolutions (example: 1920 x 820) when using hulu, netflix, amazon prime, the image shifts to the bottom right hand corner with most of the image off the screen - the upscale option works perfectly tho with these streaming services... also, the stretch function works perfectly with youtube, nfl gamepass, plex, to name a few... is there a tweak i can make that would allow the stretch option to work on hulu, netflix, prime? thanks!

**Comment by dvlden** [comment]
Hello,

I'd appreciate some screenshots and perhaps video recordings. 
You can upload them as unlisted on YT and send links here or try to upload directly here on GitHub.

Best regards.

**Comment by aeneas01** [comment]
thanks for the reply! yes, i'll try to send examples in the near future.... fwiw, the "ultrawide video" app behaves in the exact same manner, i.e. fine with the same sites as yours, and a shifted image to the bottom right (mostly off the screen) with hulu, netflix, amazon to name a few...

**Comment by aeneas01** [comment]
btw, i'm using windows 10 machine and a nvidia graphics card, the custom resolutions i use are 1920x820 and 3840x1640 - if i change these resolution back to standard, i.e. 1920x1080, your app works as expected.

![01](https://user-images.githubusercontent.com/17071068/209220784-5bef2ad1-3a45-4c50-a7c1-16d269d30269.png)

**Comment by dvlden** [comment]
That is very odd. I am unsure what causes the shift. 
Have you tried this guide?

[Extension not working?](https://github.com/dvlden/ultrawideo/discussions/62)

**Comment by dvlden** [comment]
Since v3 has been released, this repository is being deprecated/archived. 
If the problem still occurs, please open an issue on new repository:

[https://github.com/dvlden/uw-pub](https://github.com/dvlden/uw-pub)
