### ISSUE TITLE
Any Idea how to Extend to work on YoutubeTV?

### ISSUE THREAD

**Issue by MikeBarberry** [dvlden/ultrawideo#95]
## Before Opening
[Search for duplicate or closed issues](https://github.com/dvlden/ultrawideo/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Information
Include as much detail as possible for this feature and why would it be useful or required to implement it.

I'm interested in using the extension mostly on YoutubeTV. I'd be fine forking and adding it myself. Just want to know if you've already tried this.

**Comment by dvlden** [comment]
It looks like you're outside of the United States. YouTube TV is only available in the US.

If you can provide me with credentials, I can probably get-away by using VPN to access this. 
I'd very much like to make it work with YT-TV, if it's not working. 

Please let me know. `n.dvlden@gmail.com`

**Comment by MikeBarberry** [comment]
Hey, I'm in the US.

Maybe you saw my Github profile? I used to live abroad but am back now.

YTTV makes people be at the IP address of the primary account once in a
while to add them to "family plan" otherwise I'd add you so you can
investigate.

I might fork and then submit a pull request if I have time/figure it out &
if you like it you can merge?

**Comment by dvlden** [comment]
Oh that's sad. Yes, PR is most welcome if you can investigate.
Even a comment on what has to be done is just as fine. 

I'll just assume one of the two things.
1. They use custom web component which is no longer `<video />` element
2. They have some styling of their own on some of the parent elements that I have to reset completely. (daily motion has this for example)

Kind regards!

**Comment by dvlden** [comment]
Resolved in the following commit. 1ee7a07cff7920e93bbf2696fbb82c47cc18d679
Coming soon to the browser stores.
