### ISSUE TITLE
Chromecast functionality 

### ISSUE THREAD

**Issue by Mattcooper93** [dvlden/ultrawideo#98]
I’d love to use this with my chromecast instead of having to use an HDMI cable. But for some reason, it doesn’t work with chromecast unless you cast the desktop but then you’ll lose audio in the process. 

I’d love to chromecast a video on YouTube and still be able to toggle the switcher.

**Comment by dvlden** [comment]
Hello @Mattcooper93 
I do not have Chromecast so I am not sure how I'd be able to reproduce this in attempt to make it work.

However, I do believe that extensions have no effect on the Chromecast device. If that's the case, this request is not possible.
