### ISSUE TITLE
only Stretch horizontal when using Upscale (object-fit seems not work)

### ISSUE THREAD

**Issue by hsinyu-chen** [dvlden/ultrawideo#99]
object-fit seems not work anymore , I have my own extension to do this, it only Stretch horizontal now
so I download yours , same issue , your Upscale is work like Stretch now ,
did you know anything about this?
my first thought is maybe Nvidia VSR but I disabled it still same

some time when you toggle a lot times or play vid for a while it works again so confuse

### Environment
- **OS**: win 11 22H2
- **Browser**: Edge 110.0.1587.63

**Comment by zoltek2** [comment]
I have the same issue.

**Comment by dvlden** [comment]
@hsinyu-chen @zoltek2 I know nothing about it. Even if I were to install VM through Parallels Desktop, I doubt that I'd have any problems. 

Closing, as v3 is being released.
